import React, { useState } from 'react';
import Head from 'next/head'
import Navbar from '../components/navbar'
import AddItem from '../components/addItem'
import ListCards from '../components/listCards'
import AddFriend from '../components/addFriend';

const friends = [
  {
    friend: 'João das Neves',
    age: '23',
    company: 'Gugle',
    approved: true

  },
  {
    friend: 'Maria das Flores',
    age: '19',
    company: 'Gugle',
    approved: false
  },
  {
    friend: 'Apolinário do Rio',
    age: '32',
    company: 'Feici',
    approved: true
  },
];



export default function Myfriends() {
  
  return (
    <>
      <Head>
        <title>Feedback</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='h-screen'>
        <Navbar activeButton='myFriends' />
        <div className="flex flex-col space-y-4">
          <div className="flex items-center justify-between mb-4 mt-4">
            <h1 className="text-2xl text-gray-800 font-bold ml-4">Meus Amigos</h1>
            <AddItem> <AddFriend /> </AddItem>
          </div>
          {friends.map((friend, index) => (
            <ListCards 
              index={"friend"+index}
              title={friend.friend}
              approved={friend.approved}
              info1={friend.age + " anos"}
              info2={friend.company}
            />
          ))}
        </div>
      </main>
    </>
  );
}