import React, { useEffect } from 'react'
import { useRouter } from 'next/router'
import { useAuthentication } from '../components/useAuthentication'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar'

const inter = Inter({ subsets: ['latin'] })

export default function MyInformations() {
  const router = useRouter();
  const { authenticated, isLoading } = useAuthentication();

  useEffect(() => {
    if (!authenticated && !isLoading) {
      router.push('/');
    }
  }, [authenticated, isLoading, router]);

  if (isLoading) {
    return <div>Carregando...</div>;
  }

  if (!authenticated) {
    return <div>Você não está autenticado.</div>;
  }
  
  return (
    <>
      <Head>
        <title>Feedback</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar activeButton='myInformation' />
        <p>Inserir Tela de Cadastro de Informações</p>
        
      </main>
    </>
  )
}
